version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Allman
  - GLFW
  - imgui
  - kondo
  - msvc
  - MSVC
  - noprofile
  - pycache
  - qtcreator
  - relwithdebinfo
  - smod
  - Solidean
  - SOLIDEAN
  - stdlib
  - tweakable
  - workdir
ignoreWords: []
import: []
