version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aabb
  - aabbs
  - Allman
  - bary
  - blas
  - blit
  - blits
  - closesthit
  - CPPRTTI
  - CPPUNWIND
  - crossrefs
  - DXGI
  - dxil
  - Embree
  - emcc
  - emrun
  - Emscripten
  - emscripten
  - emsdk
  - fovy
  - fprofile
  - GLFW
  - hlsli
  - HRESULT
  - hwnd
  - IDXGI
  - imgui
  - initializers
  - isize
  - kondo
  - libline
  - LPARAM
  - lparam
  - lpfn
  - lpsz
  - LRESULT
  - mimalloc's
  - miscompiles
  - MSVC
  - msvc
  - noprofile
  - numthreads
  - ORBIS
  - OVERLAPPEDWINDOW
  - pessimized
  - precommit
  - pycache
  - qtcreator
  - raygen
  - raygeneration
  - raytraced
  - raytracing
  - readwrite
  - relwithdebinfo
  - rtti
  - Samp
  - samplable
  - signedness
  - singlethreaded
  - skimmable
  - slib
  - slib's
  - smod
  - SOLIDEAN
  - Solidean
  - stbd
  - stdlib
  - subresource
  - swapchain
  - TEXCOORD
  - tlas
  - toolsets
  - tweakable
  - uncompiled
  - vbuf
  - vcvars
  - venv
  - vulkan
  - WASI
  - wasi
  - WNDCLASSEXW
  - workdir
  - WPARAM
  - wparam
ignoreWords: []
import: []
