# sc_add_shader_package / sc_finalize_shader_packages -- declare a target's shader package.
#
# Included from the root CMakeLists *before* the libs, so any target can call it -- including the test
# binary of a library that shaped-shader-library itself depends on (shaped-graphics-test). That works
# because target_link_libraries resolves item names at generate time, so naming a target defined later
# is legal. The catch is the failure mode: if shaped-shader-library is never defined, CMake silently
# treats the item as a plain library name, slib's include dirs never arrive, and the error surfaces as
# a confusing missing-header inside generated code. sc_finalize_shader_packages turns that into a clear
# message at the end of configure.
#
#   sc_add_shader_package(
#       TARGET     shaped-graphics-test
#       NAME       sg_test_shaders          # package id; also the header name and the mount point
#       NAMESPACE  sg::test::shaders        # where the generated symbols live
#       SOURCE_DIR tests/shaders            # relative to the calling CMakeLists
#       LANGUAGE   hlsl
#       SHADERS
#           invert.hlsl:compute:main        # path:stage:entry_point
#           blit.hlsl:vertex:main_vs
#           blit.hlsl:fragment:main_ps
#   )
#
#   #include <sg_test_shaders.hh>
#   auto cs = sg::test::shaders::invert.compute.main->acquire(ctx);
#
# Stages are spelled exactly as sg::shader_stage (compute / vertex / fragment / raygen / ...), so the
# generator emits the enumerator instead of a string for C++ to parse back.

set(SC_SHADER_PACKAGE_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/GenerateShaderPackage.cmake"
    CACHE INTERNAL "Generator script backing sc_add_shader_package")

function(sc_add_shader_package)
    cmake_parse_arguments(PKG "" "TARGET;NAME;NAMESPACE;SOURCE_DIR;LANGUAGE" "SHADERS" ${ARGN})

    foreach(_required TARGET NAME NAMESPACE SOURCE_DIR SHADERS)
        if(NOT PKG_${_required})
            message(FATAL_ERROR "sc_add_shader_package: ${_required} is required")
        endif()
    endforeach()
    if(PKG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "sc_add_shader_package: unexpected arguments: ${PKG_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT PKG_LANGUAGE)
        set(PKG_LANGUAGE hlsl)
    endif()
    if(NOT TARGET ${PKG_TARGET})
        message(FATAL_ERROR "sc_add_shader_package: '${PKG_TARGET}' is not a target")
    endif()

    # add_custom_command(OUTPUT) attaches to the directory scope it is called from, and a function does
    # not create one -- so this must be called where the target is defined. Otherwise the outputs and the
    # target that consumes them land in different scopes and nothing builds them.
    get_target_property(_target_dir ${PKG_TARGET} SOURCE_DIR)
    if(NOT "${_target_dir}" STREQUAL "${CMAKE_CURRENT_SOURCE_DIR}")
        message(FATAL_ERROR
            "sc_add_shader_package(${PKG_TARGET}): must be called from the CMakeLists that defines the "
            "target (${_target_dir}), not from ${CMAKE_CURRENT_SOURCE_DIR}")
    endif()

    set(_source_dir "${CMAKE_CURRENT_SOURCE_DIR}/${PKG_SOURCE_DIR}")
    if(NOT IS_DIRECTORY "${_source_dir}")
        message(FATAL_ERROR "sc_add_shader_package(${PKG_NAME}): SOURCE_DIR '${_source_dir}' is not a directory")
    endif()

    # Per target, not just per name: two targets in one directory sharing a NAME would collide.
    set(_gen_dir "${CMAKE_CURRENT_BINARY_DIR}/shader-packages/${PKG_TARGET}")
    set(_manifest "${_gen_dir}/${PKG_NAME}.manifest")
    set(_gen_hh "${_gen_dir}/${PKG_NAME}.hh")
    set(_gen_cc "${_gen_dir}/${PKG_NAME}.cc")

    # The manifest carries the whole declaration, so the custom command below passes only two scalar
    # paths -- a CMake list through -D would split on its own ';' before the script saw it.
    set(_manifest_text "# Generated by sc_add_shader_package. Consumed by GenerateShaderPackage.cmake.\n")
    string(APPEND _manifest_text "NAME=${PKG_NAME}\n")
    string(APPEND _manifest_text "NAMESPACE=${PKG_NAMESPACE}\n")
    string(APPEND _manifest_text "SOURCE_DIR=${_source_dir}\n")
    string(APPEND _manifest_text "LANGUAGE=${PKG_LANGUAGE}\n")
    foreach(_shader IN LISTS PKG_SHADERS)
        string(APPEND _manifest_text "SHADER=${_shader}\n")
    endforeach()

    # file(CONFIGURE), not file(WRITE): copy-if-different, so a configure that changes nothing does not
    # bump the manifest's mtime and retrigger codegen + compile + link on every preset `dev.py check` builds.
    file(CONFIGURE OUTPUT "${_manifest}" CONTENT "${_manifest_text}" @ONLY)

    # DEPENDS covers the declared shaders; DEPFILE covers the #include closure the generator discovers.
    set(_shader_files "")
    foreach(_shader IN LISTS PKG_SHADERS)
        string(REPLACE ":" ";" _parts "${_shader}")
        list(GET _parts 0 _path)
        list(APPEND _shader_files "${_source_dir}/${_path}")
    endforeach()

    add_custom_command(
        OUTPUT "${_gen_hh}" "${_gen_cc}"
        COMMAND ${CMAKE_COMMAND} "-DMANIFEST=${_manifest}" "-DOUT_DIR=${_gen_dir}" -P "${SC_SHADER_PACKAGE_SCRIPT}"
        DEPENDS "${_manifest}" "${SC_SHADER_PACKAGE_SCRIPT}" ${_shader_files}
        DEPFILE "${_gen_dir}/${PKG_NAME}.d"
        COMMENT "[slib] shader package ${PKG_NAME} (${PKG_TARGET})"
        VERBATIM
    )

    # Plain PRIVATE sources, never a FILE_SET: the generated header lives in the binary dir, and a
    # FILE_SET hard-errors on anything outside its BASE_DIRS. It is per-target private API anyway -- to
    # publish a shader, re-expose it from your own public header (see slib's coding guidelines).
    target_sources(${PKG_TARGET} PRIVATE "${_gen_hh}" "${_gen_cc}")
    target_include_directories(${PKG_TARGET} PRIVATE "${_gen_dir}")

    if(NOT PKG_TARGET STREQUAL "shaped-shader-library")
        target_link_libraries(${PKG_TARGET} PRIVATE shaped-shader-library)
    endif()

    # Stage the DXC runtime DLLs next to any executable that declares a package. slib's dxc adapter links
    # ssc-dxc, which gives the binary a load-time import of dxcompiler.dll -- without it beside the exe the
    # process does not start at all. dxil.dll is not the imported target, so $<TARGET_RUNTIME_DLLS> alone
    # would miss it (same reasoning as shaped-shader-compiler-dxc/CMakeLists.txt).
    if(SC_HAS_DXC_COMPILER AND DXC_RUNTIME_DLLS)
        get_target_property(_type ${PKG_TARGET} TYPE)
        if(_type STREQUAL "EXECUTABLE")
            add_custom_command(TARGET ${PKG_TARGET} POST_BUILD
                COMMAND ${CMAKE_COMMAND} -E copy_if_different ${DXC_RUNTIME_DLLS} $<TARGET_FILE_DIR:${PKG_TARGET}>
                COMMAND_EXPAND_LISTS
            )
        endif()
    endif()

    # Checked by sc_finalize_shader_packages; see the header comment.
    set_property(GLOBAL APPEND PROPERTY SC_SHADER_PACKAGE_TARGETS "${PKG_TARGET}")
endfunction()

# Fails configure with an actionable message if a package was declared but slib is missing. Call once,
# at the bottom of the root CMakeLists.
function(sc_finalize_shader_packages)
    get_property(_pkg_targets GLOBAL PROPERTY SC_SHADER_PACKAGE_TARGETS)
    if(_pkg_targets AND NOT TARGET shaped-shader-library)
        list(REMOVE_DUPLICATES _pkg_targets)
        list(JOIN _pkg_targets ", " _pkg_list)
        message(FATAL_ERROR
            "sc_add_shader_package was called for [${_pkg_list}], but the shaped-shader-library target was "
            "never defined. Check the add_subdirectory order in the root CMakeLists.")
    endif()
endfunction()
