#pragma once

/// Umbrella include for shaped-graphics' public surface; backends add their own headers.
/// Prefer the specific header you need.

#include <shaped-graphics/binding/binding.hh>
#include <shaped-graphics/binding/binding_group.hh>
#include <shaped-graphics/binding/binding_group_layout.hh>
#include <shaped-graphics/binding/bindless_array.hh>
#include <shaped-graphics/binding/compiled_shader.hh>
#include <shaped-graphics/binding/pipeline_layout.hh>
#include <shaped-graphics/binding/staging_binding_group.hh>
#include <shaped-graphics/bytes_future.hh>
#include <shaped-graphics/command_list/command_list.hh>
#include <shaped-graphics/command_list/compute.hh>
#include <shaped-graphics/command_list/copy.hh>
#include <shaped-graphics/command_list/download.hh>
#include <shaped-graphics/command_list/query.hh>
#include <shaped-graphics/command_list/raster.hh>
#include <shaped-graphics/command_list/raytracing.hh>
#include <shaped-graphics/command_list/upload.hh>
#include <shaped-graphics/compute/compute_pipeline.hh>
#include <shaped-graphics/context/cached.hh>
#include <shaped-graphics/context/context.hh>
#include <shaped-graphics/context/persistent.hh>
#include <shaped-graphics/context/pipeline_cache.hh>
#include <shaped-graphics/context/transient.hh>
#include <shaped-graphics/context/uncached.hh>
#include <shaped-graphics/context/upload.hh>
#include <shaped-graphics/exceptions.hh>
#include <shaped-graphics/fwd.hh>
#include <shaped-graphics/memory/allocation_info.hh>
#include <shaped-graphics/memory/memory_heap.hh>
#include <shaped-graphics/present/swapchain.hh>
#include <shaped-graphics/query/gpu_timestamp.hh>
#include <shaped-graphics/raster/blend_state.hh>
#include <shaped-graphics/raster/depth_stencil_state.hh>
#include <shaped-graphics/raster/primitive_topology.hh>
#include <shaped-graphics/raster/raster_pipeline.hh>
#include <shaped-graphics/raster/rasterization_state.hh>
#include <shaped-graphics/raster/vertex_input.hh>
#include <shaped-graphics/raytracing/acceleration_structure.hh>
#include <shaped-graphics/raytracing/raytracing_pipeline.hh>
#include <shaped-graphics/raytracing/raytracing_shader_table.hh>
#include <shaped-graphics/resource/buffer.hh>
#include <shaped-graphics/resource/pixel_format.hh>
#include <shaped-graphics/resource/raw_buffer.hh>
#include <shaped-graphics/resource/raw_texture.hh>
#include <shaped-graphics/resource/texture.hh>
#include <shaped-graphics/resource/views.hh>
#include <shaped-graphics/routine/reload_generation.hh>
#include <shaped-graphics/routine/render_routine.hh>
#include <shaped-graphics/routine/routine_registry.hh>
#include <shaped-graphics/types.hh>
