#pragma once

#include <clean-core/container/span.hh>
#include <clean-core/container/vector.hh>
#include <clean-core/string/string.hh>
#include <clean-core/string/string_view.hh>
#include <shaped-linter/fwd.hh>

namespace scl
{
struct baseline_group;

/// The marker lines around a generated block.
/// Everything between them belongs to the generator and is rewritten on every run; everything else in the
/// file is a human's and is never touched.
inline constexpr cc::string_view k_baseline_begin = "  # --- baseline begin: generated by `dev.py lint bless-includes` "
                                                    "— curate by moving entries above this line ---";
inline constexpr cc::string_view k_baseline_end = "  # --- baseline end ---";
} // namespace scl

/// Every include one config file has to bless for the tree below it to be green.
/// `includes` is deduplicated case-insensitively (the spelling kept is the first one seen) and sorted.
struct scl::baseline_group
{
    cc::string config_path;
    cc::vector<cc::string> includes;
};

namespace scl
{

/// Add one include to the group for `config_path`, creating it if this is the first.
/// Case-insensitive: `<DbgHelp.h>` and `<dbghelp.h>` are the same header, and one entry blesses both.
void add_to_baseline(cc::vector<baseline_group>& groups, cc::string_view config_path, cc::string_view include);

/// Sort the groups and each one's includes, so a re-run reproduces its output byte for byte.
void sort_baseline(cc::vector<baseline_group>& groups);

/// The `- kind: allow-include` entries for `includes`, marker lines included.
cc::string render_baseline_block(cc::span<cc::string const> includes);

/// `config_text` with its baseline block replaced by the one for `includes`.
///
/// A previous block is found by its markers and rewritten in place, so curated entries above it survive.
/// With no previous block the new one is appended, under a `rules:` key added if the file had none — which
/// is why the generated block always sits at the END of a config file.
///
/// An empty `includes` removes the block rather than leaving an empty one behind.
cc::string apply_baseline_block(cc::string_view config_text, cc::span<cc::string const> includes);

} // namespace scl
