# cimd_dispatch: compile a templated algorithm once per clean-simd kernel and pick one per CPU at run time.
#
#   cimd_dispatch(<target> NAME <name> HEADER <header> FUNCTION <template> [LINK <libraries>...])
#
# HEADER defines `template <class K> R FUNCTION(Args...)` and `CIMD_DISPATCH_DECLARE(NAME, FUNCTION)`; its signature
# must not depend on K. Callers write `CIMD_DISPATCH(NAME)(args...)`. LINK is what the header's code needs; clean-simd
# is always added.
#
# Kernels at or below the build's floor are instantiated in a generated TU added to <target>, compiled with its flags.
# Each kernel in SC_SIMD_DISPATCH_KERNELS — the ones above the floor — gets a generated TU of its own, compiled with
# that kernel's -march, in a static library linked behind <target>.
# A library rather than objects: its members are seen after the target's own objects, so wherever a kernel TU and a
# floor TU both emit an inline function, the linker keeps the floor's copy, which every CPU can run.
#
# A kernel TU holds nothing but the instantiation, takes no precompiled header (one built for the floor's flags would
# not match), and is never part of an LTO unit.

function(cimd_dispatch target)
    cmake_parse_arguments(ARG "" "NAME;HEADER;FUNCTION" "LINK" ${ARGN})
    foreach(_required NAME HEADER FUNCTION)
        if(NOT ARG_${_required})
            message(FATAL_ERROR "cimd_dispatch(${target}): ${_required} is required")
        endif()
    endforeach()

    get_filename_component(_header "${ARG_HEADER}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    set(_dir "${CMAKE_CURRENT_BINARY_DIR}/cimd-dispatch")
    set(_fn "${ARG_FUNCTION}")
    set(_name "${ARG_NAME}")

    # The floor TU: the table, every kernel this build's flags allow, and an extern entry per dispatched kernel.
    set(_externs "")
    set(_rows "")
    foreach(_k IN LISTS SC_SIMD_DISPATCH_KERNELS)
        string(APPEND _externs "extern cimd_fn_t const cimd_entry_${_name}_${_k};\n")
        string(APPEND _rows "        {cimd::kernel_id::${_k}, cimd_entry_${_name}_${_k}},\n")
    endforeach()
    file(CONFIGURE OUTPUT "${_dir}/${_name}-dispatch.cc" @ONLY CONTENT [=[
// GENERATED by cimd_dispatch (libs/base/clean-simd/cmake/Dispatch.cmake) — do not edit.
// The dispatch table for @_name@: the kernels this build's flags allow, then the ones compiled above them.
#include <clean-simd/dispatch.hh>
#include "@_header@"

using cimd_fn_t = decltype(&@_fn@<cimd::scalar>);
@_externs@
cimd_fn_t cimd_dispatch_@_name@()
{
    static cimd::impl::dispatch_entry<cimd_fn_t> const table[] = {
        {cimd::kernel_id::scalar, &@_fn@<cimd::scalar>},
#if CIMD_HAS_SSE2
        {cimd::kernel_id::sse2, &@_fn@<cimd::sse2>},
#endif
#if CIMD_HAS_SSE42
        {cimd::kernel_id::sse42, &@_fn@<cimd::sse42>},
#endif
#if CIMD_HAS_AVX2
        {cimd::kernel_id::avx2, &@_fn@<cimd::avx2>},
#endif
#if CIMD_HAS_AVX512
        {cimd::kernel_id::avx512, &@_fn@<cimd::avx512>},
#endif
#if CIMD_HAS_NEON
        {cimd::kernel_id::neon, &@_fn@<cimd::neon>},
#endif
#if CIMD_HAS_SIMD128
        {cimd::kernel_id::simd128, &@_fn@<cimd::simd128>},
#endif
@_rows@    };
    static cimd_fn_t const best = cimd::impl::best_entry(table);
    return cimd::impl::dispatch_select(table, best);
}
]=])
    target_sources(${target} PRIVATE "${_dir}/${_name}-dispatch.cc")
    target_link_libraries(${target} PRIVATE clean-simd)

    if(NOT SC_SIMD_DISPATCH_KERNELS)
        return()
    endif()

    set(_kernel_sources "")
    foreach(_k IN LISTS SC_SIMD_DISPATCH_KERNELS)
        set(_source "${_dir}/${_name}-${_k}.cc")
        file(CONFIGURE OUTPUT "${_source}" @ONLY CONTENT [=[
// GENERATED by cimd_dispatch (libs/base/clean-simd/cmake/Dispatch.cmake) — do not edit.
// @_name@ for the @_k@ kernel, compiled with its flags; nothing else belongs in this TU.
#include "@_header@"

extern decltype(&@_fn@<cimd::scalar>) const cimd_entry_@_name@_@_k@;
decltype(&@_fn@<cimd::scalar>) const cimd_entry_@_name@_@_k@ = &@_fn@<cimd::@_k@>;
]=])
        set_source_files_properties("${_source}" PROPERTIES COMPILE_OPTIONS "${SC_SIMD_KERNEL_FLAGS_${_k}}")
        list(APPEND _kernel_sources "${_source}")
    endforeach()

    set(_lib "${target}-cimd-${_name}")
    set_property(GLOBAL APPEND PROPERTY CIMD_KERNEL_OBJECTS ${_kernel_sources})
    add_library(${_lib} STATIC ${_kernel_sources})
    target_link_libraries(${_lib} PRIVATE clean-simd ${ARG_LINK})
    set_target_properties(${_lib} PROPERTIES INTERPROCEDURAL_OPTIMIZATION OFF)
    target_link_libraries(${target} PRIVATE ${_lib})
endfunction()

# cimd_check_link_map: fail <executable>'s build when its linker kept a kernel TU's copy of a function shared with the
# floor — the one way dispatch can put a kernel's instructions on a path every CPU runs.
#
#   cimd_check_link_map(<executable>)
#
# The final link writes a map naming where every kept symbol came from, and tools/check-link-map.py reads it.
# A symbol whose mangled name carries a dispatched kernel's type (`cimd::avx512`) can only come from that kernel's TU,
# and so can the cimd_entry_* pointers; anything else that a kernel TU supplied is a finding.
function(cimd_check_link_map executable)
    if(NOT SC_SIMD_DISPATCH_KERNELS)
        return()
    endif()
    set(_map "$<TARGET_FILE_DIR:${executable}>/$<TARGET_FILE_BASE_NAME:${executable}>.map")
    if(MSVC)
        target_link_options(${executable} PRIVATE "/MAP:${_map}")
    elseif(APPLE)
        # Apple has no x86-64 floor below a dispatched kernel to protect.
        return()
    else()
        target_link_options(${executable} PRIVATE "LINKER:-Map=${_map}")
    endif()

    get_property(_objects GLOBAL PROPERTY CIMD_KERNEL_OBJECTS)
    set(_args "")
    foreach(_k IN LISTS SC_SIMD_DISPATCH_KERNELS)
        list(APPEND _args --kernel ${_k})
    endforeach()
    foreach(_o IN LISTS _objects)
        get_filename_component(_o "${_o}" NAME)
        list(APPEND _args --object ${_o})
    endforeach()
    add_custom_command(TARGET ${executable} POST_BUILD
        COMMAND uv run "${CMAKE_SOURCE_DIR}/libs/base/clean-simd/tools/check-link-map.py" --map "${_map}" ${_args}
        COMMENT "cimd: checking ${executable}'s link map for kernel code on a floor path"
        VERBATIM)
endfunction()
