// GENERATED by `sgl pipeline-fields` from the SGL prelude's mirror of sg::raster_pipeline_description.
// Never edit it: `uv run dev.py check sgl-prelude --fix` rewrites it, and the check fails while it differs.
// Every setter names an sg field and every case an sg enumerator, so a mirror that drifted from sg does not compile.
#pragma once

// clang-format off

#include <shaped-shader-library/impl/pipeline_field_support.hh>

namespace slib::impl::fields
{
// ---- one setter per field; a generated pipeline calls these directly

inline void topology(sg::raster_pipeline_description& d, sg::primitive_topology v) { d.topology = v; }
inline void patch_control_points(sg::raster_pipeline_description& d, int v) { d.patch_control_points = decltype(d.patch_control_points)(v); }
inline void rasterization_fill(sg::raster_pipeline_description& d, sg::fill_mode v) { d.rasterization.fill = v; }
inline void rasterization_cull(sg::raster_pipeline_description& d, sg::cull_mode v) { d.rasterization.cull = v; }
inline void rasterization_front(sg::raster_pipeline_description& d, sg::front_face v) { d.rasterization.front = v; }
inline void rasterization_depth_clip_enabled(sg::raster_pipeline_description& d, bool v) { d.rasterization.depth_clip_enabled = v; }
inline void rasterization_depth_bias(sg::raster_pipeline_description& d, float v) { d.rasterization.depth_bias = v; }
inline void rasterization_depth_bias_slope(sg::raster_pipeline_description& d, float v) { d.rasterization.depth_bias_slope = v; }
inline void rasterization_depth_bias_clamp(sg::raster_pipeline_description& d, float v) { d.rasterization.depth_bias_clamp = v; }
inline void depth_stencil_depth_test(sg::raster_pipeline_description& d, bool v) { d.depth_stencil.depth_test = v; }
inline void depth_stencil_depth_write(sg::raster_pipeline_description& d, bool v) { d.depth_stencil.depth_write = v; }
inline void depth_stencil_depth_compare(sg::raster_pipeline_description& d, sg::compare_op v) { d.depth_stencil.depth_compare = v; }
inline void depth_stencil_stencil_test(sg::raster_pipeline_description& d, bool v) { d.depth_stencil.stencil_test = v; }
inline void depth_stencil_stencil_read_mask(sg::raster_pipeline_description& d, int v) { d.depth_stencil.stencil_read_mask = decltype(d.depth_stencil.stencil_read_mask)(v); }
inline void depth_stencil_stencil_write_mask(sg::raster_pipeline_description& d, int v) { d.depth_stencil.stencil_write_mask = decltype(d.depth_stencil.stencil_write_mask)(v); }
inline void depth_stencil_stencil_front_fail(sg::raster_pipeline_description& d, sg::stencil_op v) { d.depth_stencil.stencil_front.fail = v; }
inline void depth_stencil_stencil_front_depth_fail(sg::raster_pipeline_description& d, sg::stencil_op v) { d.depth_stencil.stencil_front.depth_fail = v; }
inline void depth_stencil_stencil_front_pass(sg::raster_pipeline_description& d, sg::stencil_op v) { d.depth_stencil.stencil_front.pass = v; }
inline void depth_stencil_stencil_front_compare(sg::raster_pipeline_description& d, sg::compare_op v) { d.depth_stencil.stencil_front.compare = v; }
inline void depth_stencil_stencil_back_fail(sg::raster_pipeline_description& d, sg::stencil_op v) { d.depth_stencil.stencil_back.fail = v; }
inline void depth_stencil_stencil_back_depth_fail(sg::raster_pipeline_description& d, sg::stencil_op v) { d.depth_stencil.stencil_back.depth_fail = v; }
inline void depth_stencil_stencil_back_pass(sg::raster_pipeline_description& d, sg::stencil_op v) { d.depth_stencil.stencil_back.pass = v; }
inline void depth_stencil_stencil_back_compare(sg::raster_pipeline_description& d, sg::compare_op v) { d.depth_stencil.stencil_back.compare = v; }
inline void color_targets_format(sg::raster_pipeline_description& d, int target, sg::pixel_format v) { d.color_targets[target].format = v; }
inline void color_targets_blend_color_source(sg::raster_pipeline_description& d, int target, sg::blend_factor v) { engaged(d.color_targets[target]).color.source = v; }
inline void color_targets_blend_color_target(sg::raster_pipeline_description& d, int target, sg::blend_factor v) { engaged(d.color_targets[target]).color.target = v; }
inline void color_targets_blend_color_op(sg::raster_pipeline_description& d, int target, sg::blend_op v) { engaged(d.color_targets[target]).color.op = v; }
inline void color_targets_blend_alpha_source(sg::raster_pipeline_description& d, int target, sg::blend_factor v) { engaged(d.color_targets[target]).alpha.source = v; }
inline void color_targets_blend_alpha_target(sg::raster_pipeline_description& d, int target, sg::blend_factor v) { engaged(d.color_targets[target]).alpha.target = v; }
inline void color_targets_blend_alpha_op(sg::raster_pipeline_description& d, int target, sg::blend_op v) { engaged(d.color_targets[target]).alpha.op = v; }
inline void color_targets_write_mask_r(sg::raster_pipeline_description& d, int target, bool v) { d.color_targets[target].write_mask.set(sg::color_channel::r, v); }
inline void color_targets_write_mask_g(sg::raster_pipeline_description& d, int target, bool v) { d.color_targets[target].write_mask.set(sg::color_channel::g, v); }
inline void color_targets_write_mask_b(sg::raster_pipeline_description& d, int target, bool v) { d.color_targets[target].write_mask.set(sg::color_channel::b, v); }
inline void color_targets_write_mask_a(sg::raster_pipeline_description& d, int target, bool v) { d.color_targets[target].write_mask.set(sg::color_channel::a, v); }
inline void depth_stencil_format(sg::raster_pipeline_description& d, sg::pixel_format v) { d.depth_stencil_format = v; }
inline void sample_count(sg::raster_pipeline_description& d, int v) { d.sample_count = decltype(d.sample_count)(v); }
/// `blend = .none`: the target does not blend.
inline void color_targets_blend_none(sg::raster_pipeline_description& d, int target) { d.color_targets[target].blend = {}; }

// ---- each enum's cases by name, for a reload

inline constexpr enum_case cases_primitive_topology[] = {
    {"point_list", int(sg::primitive_topology::point_list)},
    {"line_list", int(sg::primitive_topology::line_list)},
    {"line_strip", int(sg::primitive_topology::line_strip)},
    {"triangle_list", int(sg::primitive_topology::triangle_list)},
    {"triangle_strip", int(sg::primitive_topology::triangle_strip)},
    {"patch_list", int(sg::primitive_topology::patch_list)},
};
inline constexpr enum_case cases_fill_mode[] = {
    {"solid", int(sg::fill_mode::solid)},
    {"wireframe", int(sg::fill_mode::wireframe)},
};
inline constexpr enum_case cases_cull_mode[] = {
    {"none", int(sg::cull_mode::none)},
    {"front", int(sg::cull_mode::front)},
    {"back", int(sg::cull_mode::back)},
};
inline constexpr enum_case cases_front_face[] = {
    {"counter_clockwise", int(sg::front_face::counter_clockwise)},
    {"clockwise", int(sg::front_face::clockwise)},
};
inline constexpr enum_case cases_compare_op[] = {
    {"never", int(sg::compare_op::never)},
    {"less", int(sg::compare_op::less)},
    {"equal", int(sg::compare_op::equal)},
    {"less_equal", int(sg::compare_op::less_equal)},
    {"greater", int(sg::compare_op::greater)},
    {"not_equal", int(sg::compare_op::not_equal)},
    {"greater_equal", int(sg::compare_op::greater_equal)},
    {"always", int(sg::compare_op::always)},
};
inline constexpr enum_case cases_stencil_op[] = {
    {"keep", int(sg::stencil_op::keep)},
    {"zero", int(sg::stencil_op::zero)},
    {"replace", int(sg::stencil_op::replace)},
    {"increment_clamp", int(sg::stencil_op::increment_clamp)},
    {"decrement_clamp", int(sg::stencil_op::decrement_clamp)},
    {"invert", int(sg::stencil_op::invert)},
    {"increment_wrap", int(sg::stencil_op::increment_wrap)},
    {"decrement_wrap", int(sg::stencil_op::decrement_wrap)},
};
inline constexpr enum_case cases_pixel_format[] = {
    {"undefined", int(sg::pixel_format::undefined)},
    {"r8_unorm", int(sg::pixel_format::r8_unorm)},
    {"r8_snorm", int(sg::pixel_format::r8_snorm)},
    {"r8_uint", int(sg::pixel_format::r8_uint)},
    {"r8_sint", int(sg::pixel_format::r8_sint)},
    {"rg8_unorm", int(sg::pixel_format::rg8_unorm)},
    {"rg8_snorm", int(sg::pixel_format::rg8_snorm)},
    {"rg8_uint", int(sg::pixel_format::rg8_uint)},
    {"rg8_sint", int(sg::pixel_format::rg8_sint)},
    {"rgba8_unorm", int(sg::pixel_format::rgba8_unorm)},
    {"rgba8_snorm", int(sg::pixel_format::rgba8_snorm)},
    {"rgba8_uint", int(sg::pixel_format::rgba8_uint)},
    {"rgba8_sint", int(sg::pixel_format::rgba8_sint)},
    {"rgba8_unorm_srgb", int(sg::pixel_format::rgba8_unorm_srgb)},
    {"bgra8_unorm", int(sg::pixel_format::bgra8_unorm)},
    {"bgra8_unorm_srgb", int(sg::pixel_format::bgra8_unorm_srgb)},
    {"r16_float", int(sg::pixel_format::r16_float)},
    {"r16_uint", int(sg::pixel_format::r16_uint)},
    {"r16_sint", int(sg::pixel_format::r16_sint)},
    {"rg16_float", int(sg::pixel_format::rg16_float)},
    {"rg16_uint", int(sg::pixel_format::rg16_uint)},
    {"rg16_sint", int(sg::pixel_format::rg16_sint)},
    {"rgba16_float", int(sg::pixel_format::rgba16_float)},
    {"rgba16_uint", int(sg::pixel_format::rgba16_uint)},
    {"rgba16_sint", int(sg::pixel_format::rgba16_sint)},
    {"r32_float", int(sg::pixel_format::r32_float)},
    {"r32_uint", int(sg::pixel_format::r32_uint)},
    {"r32_sint", int(sg::pixel_format::r32_sint)},
    {"rg32_float", int(sg::pixel_format::rg32_float)},
    {"rg32_uint", int(sg::pixel_format::rg32_uint)},
    {"rg32_sint", int(sg::pixel_format::rg32_sint)},
    {"rgba32_float", int(sg::pixel_format::rgba32_float)},
    {"rgba32_uint", int(sg::pixel_format::rgba32_uint)},
    {"rgba32_sint", int(sg::pixel_format::rgba32_sint)},
    {"rgb10a2_unorm", int(sg::pixel_format::rgb10a2_unorm)},
    {"rg11b10_float", int(sg::pixel_format::rg11b10_float)},
    {"depth16_unorm", int(sg::pixel_format::depth16_unorm)},
    {"depth32_float", int(sg::pixel_format::depth32_float)},
    {"depth32_float_stencil8", int(sg::pixel_format::depth32_float_stencil8)},
    {"bc1_rgba_unorm", int(sg::pixel_format::bc1_rgba_unorm)},
    {"bc1_rgba_unorm_srgb", int(sg::pixel_format::bc1_rgba_unorm_srgb)},
    {"bc2_unorm", int(sg::pixel_format::bc2_unorm)},
    {"bc2_unorm_srgb", int(sg::pixel_format::bc2_unorm_srgb)},
    {"bc3_unorm", int(sg::pixel_format::bc3_unorm)},
    {"bc3_unorm_srgb", int(sg::pixel_format::bc3_unorm_srgb)},
    {"bc4_r_unorm", int(sg::pixel_format::bc4_r_unorm)},
    {"bc4_r_snorm", int(sg::pixel_format::bc4_r_snorm)},
    {"bc5_rg_unorm", int(sg::pixel_format::bc5_rg_unorm)},
    {"bc5_rg_snorm", int(sg::pixel_format::bc5_rg_snorm)},
    {"bc6h_rgb_ufloat", int(sg::pixel_format::bc6h_rgb_ufloat)},
    {"bc6h_rgb_sfloat", int(sg::pixel_format::bc6h_rgb_sfloat)},
    {"bc7_rgba_unorm", int(sg::pixel_format::bc7_rgba_unorm)},
    {"bc7_rgba_unorm_srgb", int(sg::pixel_format::bc7_rgba_unorm_srgb)},
};
inline constexpr enum_case cases_blend_factor[] = {
    {"zero", int(sg::blend_factor::zero)},
    {"one", int(sg::blend_factor::one)},
    {"src_color", int(sg::blend_factor::src_color)},
    {"one_minus_src_color", int(sg::blend_factor::one_minus_src_color)},
    {"dst_color", int(sg::blend_factor::dst_color)},
    {"one_minus_dst_color", int(sg::blend_factor::one_minus_dst_color)},
    {"src_alpha", int(sg::blend_factor::src_alpha)},
    {"one_minus_src_alpha", int(sg::blend_factor::one_minus_src_alpha)},
    {"dst_alpha", int(sg::blend_factor::dst_alpha)},
    {"one_minus_dst_alpha", int(sg::blend_factor::one_minus_dst_alpha)},
};
inline constexpr enum_case cases_blend_op[] = {
    {"add", int(sg::blend_op::add)},
    {"subtract", int(sg::blend_op::subtract)},
    {"reverse_subtract", int(sg::blend_op::reverse_subtract)},
    {"min", int(sg::blend_op::min)},
    {"max", int(sg::blend_op::max)},
};
inline constexpr named_enum enums[] = {
    {"primitive_topology", cases_primitive_topology},
    {"fill_mode", cases_fill_mode},
    {"cull_mode", cases_cull_mode},
    {"front_face", cases_front_face},
    {"compare_op", cases_compare_op},
    {"stencil_op", cases_stencil_op},
    {"pixel_format", cases_pixel_format},
    {"blend_factor", cases_blend_factor},
    {"blend_op", cases_blend_op},
};

// ---- every field by its path, `*` for a target: what a reloaded setting is applied through

inline constexpr field all[] = {
    {"topology", field_kind::enum_case, cases_primitive_topology, [](sg::raster_pipeline_description& d, int, field_value v) { topology(d, sg::primitive_topology(v.integer)); }},
    {"patch_control_points", field_kind::integer, {}, [](sg::raster_pipeline_description& d, int, field_value v) { patch_control_points(d, int(v.integer)); }},
    {"rasterization.fill", field_kind::enum_case, cases_fill_mode, [](sg::raster_pipeline_description& d, int, field_value v) { rasterization_fill(d, sg::fill_mode(v.integer)); }},
    {"rasterization.cull", field_kind::enum_case, cases_cull_mode, [](sg::raster_pipeline_description& d, int, field_value v) { rasterization_cull(d, sg::cull_mode(v.integer)); }},
    {"rasterization.front", field_kind::enum_case, cases_front_face, [](sg::raster_pipeline_description& d, int, field_value v) { rasterization_front(d, sg::front_face(v.integer)); }},
    {"rasterization.depth_clip_enabled", field_kind::boolean, {}, [](sg::raster_pipeline_description& d, int, field_value v) { rasterization_depth_clip_enabled(d, v.integer != 0); }},
    {"rasterization.depth_bias", field_kind::real, {}, [](sg::raster_pipeline_description& d, int, field_value v) { rasterization_depth_bias(d, float(v.real)); }},
    {"rasterization.depth_bias_slope", field_kind::real, {}, [](sg::raster_pipeline_description& d, int, field_value v) { rasterization_depth_bias_slope(d, float(v.real)); }},
    {"rasterization.depth_bias_clamp", field_kind::real, {}, [](sg::raster_pipeline_description& d, int, field_value v) { rasterization_depth_bias_clamp(d, float(v.real)); }},
    {"depth_stencil.depth_test", field_kind::boolean, {}, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_depth_test(d, v.integer != 0); }},
    {"depth_stencil.depth_write", field_kind::boolean, {}, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_depth_write(d, v.integer != 0); }},
    {"depth_stencil.depth_compare", field_kind::enum_case, cases_compare_op, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_depth_compare(d, sg::compare_op(v.integer)); }},
    {"depth_stencil.stencil_test", field_kind::boolean, {}, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_test(d, v.integer != 0); }},
    {"depth_stencil.stencil_read_mask", field_kind::integer, {}, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_read_mask(d, int(v.integer)); }},
    {"depth_stencil.stencil_write_mask", field_kind::integer, {}, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_write_mask(d, int(v.integer)); }},
    {"depth_stencil.stencil_front.fail", field_kind::enum_case, cases_stencil_op, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_front_fail(d, sg::stencil_op(v.integer)); }},
    {"depth_stencil.stencil_front.depth_fail", field_kind::enum_case, cases_stencil_op, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_front_depth_fail(d, sg::stencil_op(v.integer)); }},
    {"depth_stencil.stencil_front.pass", field_kind::enum_case, cases_stencil_op, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_front_pass(d, sg::stencil_op(v.integer)); }},
    {"depth_stencil.stencil_front.compare", field_kind::enum_case, cases_compare_op, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_front_compare(d, sg::compare_op(v.integer)); }},
    {"depth_stencil.stencil_back.fail", field_kind::enum_case, cases_stencil_op, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_back_fail(d, sg::stencil_op(v.integer)); }},
    {"depth_stencil.stencil_back.depth_fail", field_kind::enum_case, cases_stencil_op, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_back_depth_fail(d, sg::stencil_op(v.integer)); }},
    {"depth_stencil.stencil_back.pass", field_kind::enum_case, cases_stencil_op, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_back_pass(d, sg::stencil_op(v.integer)); }},
    {"depth_stencil.stencil_back.compare", field_kind::enum_case, cases_compare_op, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_stencil_back_compare(d, sg::compare_op(v.integer)); }},
    {"color_targets.*.format", field_kind::enum_case, cases_pixel_format, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_format(d, target, sg::pixel_format(v.integer)); }},
    {"color_targets.*.blend.color.source", field_kind::enum_case, cases_blend_factor, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_blend_color_source(d, target, sg::blend_factor(v.integer)); }},
    {"color_targets.*.blend.color.target", field_kind::enum_case, cases_blend_factor, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_blend_color_target(d, target, sg::blend_factor(v.integer)); }},
    {"color_targets.*.blend.color.op", field_kind::enum_case, cases_blend_op, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_blend_color_op(d, target, sg::blend_op(v.integer)); }},
    {"color_targets.*.blend.alpha.source", field_kind::enum_case, cases_blend_factor, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_blend_alpha_source(d, target, sg::blend_factor(v.integer)); }},
    {"color_targets.*.blend.alpha.target", field_kind::enum_case, cases_blend_factor, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_blend_alpha_target(d, target, sg::blend_factor(v.integer)); }},
    {"color_targets.*.blend.alpha.op", field_kind::enum_case, cases_blend_op, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_blend_alpha_op(d, target, sg::blend_op(v.integer)); }},
    {"color_targets.*.write_mask.r", field_kind::boolean, {}, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_write_mask_r(d, target, v.integer != 0); }},
    {"color_targets.*.write_mask.g", field_kind::boolean, {}, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_write_mask_g(d, target, v.integer != 0); }},
    {"color_targets.*.write_mask.b", field_kind::boolean, {}, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_write_mask_b(d, target, v.integer != 0); }},
    {"color_targets.*.write_mask.a", field_kind::boolean, {}, [](sg::raster_pipeline_description& d, int target, field_value v) { color_targets_write_mask_a(d, target, v.integer != 0); }},
    {"depth_stencil_format", field_kind::enum_case, cases_pixel_format, [](sg::raster_pipeline_description& d, int, field_value v) { depth_stencil_format(d, sg::pixel_format(v.integer)); }},
    {"sample_count", field_kind::integer, {}, [](sg::raster_pipeline_description& d, int, field_value v) { sample_count(d, int(v.integer)); }},
    {"color_targets.*.blend", field_kind::none, {}, [](sg::raster_pipeline_description& d, int target, field_value) { color_targets_blend_none(d, target); }},
};
} // namespace slib::impl::fields

// clang-format on
