"""C++ text: the register layer per kernel, and the kernel-agnostic fixed layer per element.

The fixed layer depends only on the element and the register count, never on the kernel: `simd<f32, N, K>` with two
registers is the same code whether the registers are SSE, NEON or 128-bit arrays.
So it is emitted once per (element, register count), as a partial specialization constrained on that count, and every
kernel reaches it through `impl::reg<T, K, Bits>`.
"""

from __future__ import annotations

from . import arm, scalar, wasm, x86
from .model import (BINARY_OPERATORS, COMPARE_OPERATORS, ELEM, ELEMS, KERNELS, LANE_BITS, MASK_SIGNATURES, REFERENCE,
                    REGISTER_COUNTS, SHORT, SIGNATURES, SINGLE, UNARY_OPERATORS, Elem, Kernel, ops_of)

COMMAND = "uv run libs/base/clean-simd/tools/gen-simd.py --write"


def module(kernel: str):
    if kernel == "scalar":
        return scalar
    if kernel == "neon":
        return arm
    if kernel == "simd128":
        return wasm
    return x86


def header(purpose: str) -> list[str]:
    return [f"// GENERATED by {COMMAND} — do not edit.", f"// {purpose}", "#pragma once", ""]


def has_operator(e: Elem, op: str) -> bool:
    """The operator rule: every reference kernel implements `op` as SINGLE or SHORT."""
    for kernel, w in REFERENCE:
        impl = module(kernel).ops(kernel, e, w).get(op)
        if impl is None or impl.cost not in (SINGLE, SHORT):
            return False
    return True


# --- register layer ---------------------------------------------------------------------------------------------


def _signature(name: str, table: dict[str, tuple[str, str]], e: Elem | None, mod, w: int) -> tuple[str, str]:
    ret, params = table[name]
    if ret.startswith("to:"):
        ret = mod.reg_type(ELEM[ret[3:]], w)
    if e is not None:
        ret = ret.replace("E", e.name) if ret == "E" else ret
        params = params.replace("E ", f"{e.name} ").replace("E* ", f"{e.name}* ")
    return ret, params


def emit_reg(k: Kernel, e: Elem, w: int) -> list[str]:
    mod = module(k.name)
    ops = mod.ops(k.name, e, w)
    missing = [op for op in ops_of(e) if op not in ops]
    assert not missing, f"{k.name} {e.name}@{w} lacks {missing}"
    lines = [
        "template <>",
        f"struct cimd::impl::reg<cimd::{e.name}, cimd::{k.name}, {w}>",
        "{",
        f"    using type = {mod.reg_type(e, w)};",
        f"    using mr = mreg<{e.bits}, {k.name}, {w}>;",
        "    using mtype = mr::type;",
        f"    static constexpr int lanes = {w // e.bits};",
        "",
    ]
    for name in ops_of(e):
        ret, params = _signature(name, SIGNATURES, e, mod, w)
        body = "\n".join("        " + line for line in ops[name].body.split("\n"))
        lines += [f"    static CC_FORCE_INLINE {ret} {name}({params})", "    {", body, "    }"]
    lines += ["};", ""]
    return lines


def emit_mreg(k: Kernel, lane_bits: int, w: int) -> list[str]:
    mod = module(k.name)
    ops = mod.mask_ops(k.name, lane_bits, w)
    lines = [
        "template <>",
        f"struct cimd::impl::mreg<{lane_bits}, cimd::{k.name}, {w}>",
        "{",
        f"    using type = {mod.mask_type(k.name, lane_bits, w)};",
        f"    static constexpr int lanes = {w // lane_bits};",
        "",
    ]
    for name in MASK_SIGNATURES:
        ret, params = _signature(name, MASK_SIGNATURES, None, mod, w)
        body = "\n".join("        " + line for line in ops[name].body.split("\n"))
        lines += [f"    static CC_FORCE_INLINE {ret} {name}({params})", "    {", body, "    }"]
    lines += ["};", ""]
    return lines


_SCALAR_PRELUDE = [
    "/// One 128-bit register of the scalar kernel: plain lanes, written out one by one in every operation.",
    "template <class T, int L>",
    "struct cimd::impl::scalar_reg",
    "{",
    "    T v[L];",
    "};",
    "",
    "template <int L>",
    "struct cimd::impl::scalar_mreg",
    "{",
    "    bool v[L];",
    "};",
    "",
    "namespace cimd::impl",
    "{",
    "/// Out of range is unspecified for cimd; this saturates, which keeps the C++ conversion away from its UB.",
    "CC_FORCE_INLINE i32 to_i32_lane(f32 x)",
    "{",
    "    if (!(x == x))",
    "        return 0;",
    "    if (x >= 2147483648.f)",
    "        return 2147483647;",
    "    if (x < -2147483648.f)",
    "        return -2147483647 - 1;",
    "    return i32(x);",
    "}",
    "} // namespace cimd::impl",
    "",
]


def emit_kernel(k: Kernel) -> str:
    lines = header(f"The {k.name} kernel's register layer: one static function per operation, per element and width.")
    lines += ["#include <clean-simd/impl/intrinsics.hh>", "#include <clean-simd/simd.hh>"]
    if k.name == "scalar":
        lines += ["", "#include <clean-core/math/bit.hh>"]
    lines += [""]
    if k.guard:
        lines += [f"#if {k.guard}", ""]
    lines += ["// NOLINTBEGIN", ""]
    if k.name == "scalar":
        lines += _SCALAR_PRELUDE
    for w in k.widths:
        for lane_bits in LANE_BITS:
            lines += emit_mreg(k, lane_bits, w)
        for e in ELEMS:
            lines += emit_reg(k, e, w)
    lines += ["// NOLINTEND", ""]
    if k.guard:
        lines += [f"#endif // {k.guard}", ""]
    return "\n".join(lines)


# --- fixed layer ------------------------------------------------------------------------------------------------


def _each(r: int, stmt: str) -> list[str]:
    """`stmt` written out once per register, with `{i}` the index and `{o}` its first lane."""
    return [stmt.format(i=i, o=f"{i} * reg_t::lanes" if i else "0") for i in range(r)]


def _tree(r: int, combine: str, first: str = "_r") -> list[str]:
    """Registers folded pairwise — register i with register i + r/2 — into `x0`, which the caller reduces."""
    lines = [f"auto x{i} = {first}[{i}];" for i in range(r)]
    width = r
    while width > 1:
        width //= 2
        lines += [f"x{i} = {combine.format(a=f'x{i}', b=f'x{i + width}')};" for i in range(width)]
    return lines


def _fn(signature: str, body: list[str], indent: str = "    ") -> list[str]:
    return [f"{indent}{signature}", f"{indent}{{"] + [f"{indent}    {line}" for line in body] + [f"{indent}}}"]


def emit_value(e: Elem, r: int) -> list[str]:
    t = e.name
    ops = ops_of(e)
    lines = [
        f"/// {t} lanes held in {r} register{'s' if r > 1 else ''} of whichever kernel K is.",
        "template <int N, class K>",
        f"    requires(cimd::impl::valid_shape<cimd::{t}, N> && cimd::is_available<K>"
        f" && cimd::impl::reg_count<cimd::{t}, N, K> == {r})",
        f"struct alignas(cimd::impl::alignment<cimd::{t}, N>) cimd::simd<cimd::{t}, N, K>",
        "{",
        f"    using element_t = {t};",
        "    using kernel_t = K;",
        f"    using mask_t = mask<{e.bits}, N, K>;",
        f"    using storage_t = storage<{t}, N>;",
        f"    using reg_t = impl::reg<{t}, K, impl::reg_bits<{t}, N, K>>;",
        "",
        "    static constexpr int lanes = N;",
        f"    static constexpr int registers = {r};",
        "    static constexpr bool generated = true;",
        "    static constexpr bool is_loop_free = true;",
        "",
        f"    typename reg_t::type _r[{r}];",
        "",
        "    simd() = default;",
        "",
        "    /// Broadcast; only from exactly the element type, so `v * 2.0` is an error rather than a silent conversion.",
    ]
    lines += _fn(f"CC_FORCE_INLINE simd({t} x)", ["auto const v = reg_t::broadcast(x);"] + _each(r, "_r[{i}] = v;"))
    lines += ["    template <class U>", "    simd(U) = delete;", ""]
    lines += _fn("CC_FORCE_INLINE simd(storage_t const& s)", _each(r, "_r[{i}] = reg_t::load_aligned(s.lanes + {o});"))
    lines += _fn("CC_FORCE_INLINE operator storage_t() const",
                 ["storage_t s;"] + _each(r, "reg_t::store_aligned(s.lanes + {o}, _r[{i}]);") + ["return s;"])
    lines += [""]
    lines += _fn("static CC_FORCE_INLINE simd zero()",
                 ["simd v;", "auto const z = reg_t::zero();"] + _each(r, "v._r[{i}] = z;") + ["return v;"])
    lines += ["    /// 0, 1, 2, … N - 1."]
    lines += _fn("static CC_FORCE_INLINE simd iota()",
                 ["simd v;"] + _each(r, f"v._r[{{i}}] = reg_t::iota({t}({{o}}));") + ["return v;"])
    lines += [
        "    template <class... A>",
        f"        requires(sizeof...(A) == N && (std::is_same_v<A, {t}> && ...))",
    ]
    lines += _fn("static CC_FORCE_INLINE simd from_lanes(A... v)", ["return simd(storage_t{{v...}});"])
    for name in ("load", "load_aligned"):
        lines += _fn(f"static CC_FORCE_INLINE simd {name}({t} const* p)",
                     ["simd v;"] + _each(r, f"v._r[{{i}}] = reg_t::{name}(p + {{o}});") + ["return v;"])
    for name in ("store", "store_aligned"):
        lines += _fn(f"CC_FORCE_INLINE void {name}({t}* p) const", _each(r, f"reg_t::{name}(p + {{o}}, _r[{{i}}]);"))
    lines += [""]
    lines += _fn(f"CC_FORCE_INLINE {t} lane(int i) const",
                 ['CC_ASSERT(0 <= i && i < N, "lane index out of range");', "return storage_t(*this).lanes[i];"])
    lines += _fn(f"CC_FORCE_INLINE simd with_lane(int i, {t} x) const",
                 ['CC_ASSERT(0 <= i && i < N, "lane index out of range");', "storage_t s = *this;", "s.lanes[i] = x;",
                  "return simd(s);"])
    lines += [""]

    for name in ("add", "sub", "mul", "min", "max", "bit_and", "bit_or", "bit_xor"):
        if name in ops:
            lines += _fn(f"CC_FORCE_INLINE simd {name}(simd b) const",
                         ["simd v;"] + _each(r, f"v._r[{{i}}] = reg_t::{name}(_r[{{i}}], b._r[{{i}}]);") + ["return v;"])
    for name in ("neg", "abs", "bit_not"):
        if name in ops:
            lines += _fn(f"CC_FORCE_INLINE simd {name}() const",
                         ["simd v;"] + _each(r, f"v._r[{{i}}] = reg_t::{name}(_r[{{i}}]);") + ["return v;"])
    lines += ["    /// `*this * b + c`, fused where the kernel has FMA (K::has_native_fma) and rounded twice elsewhere."]
    lines += _fn("CC_FORCE_INLINE simd mul_add(simd b, simd c) const",
                 ["simd v;"] + _each(r, "v._r[{i}] = reg_t::mul_add(_r[{i}], b._r[{i}], c._r[{i}]);") + ["return v;"])
    for name in COMPARE_OPERATORS:
        lines += _fn(f"CC_FORCE_INLINE mask_t {name}(simd b) const",
                     ["mask_t m;"] + _each(r, f"m._r[{{i}}] = reg_t::{name}(_r[{{i}}], b._r[{{i}}]);") + ["return m;"])
    lines += ["", "    /// Lane i combined with lane i + N/2, recursively, so every kernel produces the same bits."]
    for op in ("add", "min", "max"):
        lines += _fn(f"CC_FORCE_INLINE {t} reduce_{op}() const",
                     _tree(r, f"reg_t::{op}({{a}}, {{b}})") + [f"return reg_t::reduce_{op}(x0);"])
    lines += [""]

    target = "i32" if e.is_float else "f32"
    lines += [
        "    /// Lane-wise conversion to another element of the same width; float to integer truncates, and a value out of",
        "    /// range is unspecified.",
        "    template <class U>",
        f"        requires(std::is_same_v<U, {t}> || std::is_same_v<U, {target}>)",
    ]
    lines += _fn("CC_FORCE_INLINE simd<U, N, K> convert() const",
                 [f"if constexpr (std::is_same_v<U, {t}>)", "    return *this;", "else", "{",
                  "    simd<U, N, K> v;"]
                 + ["    " + s for s in _each(r, f"v._r[{{i}}] = reg_t::to_{target}(_r[{{i}}]);")]
                 + ["    return v;", "}"])
    lines += [""]

    # operators: a hidden friend per operation the rule allows, and the member twin always
    for name, sym in BINARY_OPERATORS.items():
        if name in ops and has_operator(e, name):
            lines += [f"    CC_FORCE_INLINE friend simd operator{sym}(simd a, simd b) {{ return a.{name}(b); }}",
                      f"    CC_FORCE_INLINE simd& operator{sym}=(simd b) {{ return *this = {name}(b); }}"]
    for name, sym in UNARY_OPERATORS.items():
        if name in ops and has_operator(e, name):
            lines += [f"    CC_FORCE_INLINE friend simd operator{sym}(simd a) {{ return a.{name}(); }}"]
    for name, sym in COMPARE_OPERATORS.items():
        if has_operator(e, name):
            lines += [f"    CC_FORCE_INLINE friend mask_t operator{sym}(simd a, simd b) {{ return a.{name}(b); }}"]
    lines += ["};", ""]
    return lines


def emit_mask(lane_bits: int, r: int) -> list[str]:
    lines = [
        f"/// A mask over {lane_bits}-bit lanes, in {r} mask register{'s' if r > 1 else ''} of whichever kernel K is.",
        "template <int N, class K>",
        f"    requires(N > 0 && (N & (N - 1)) == 0 && N * {lane_bits} >= 128 && cimd::is_available<K>"
        f" && cimd::impl::lane_reg_count<{lane_bits}, N, K> == {r})",
        f"struct cimd::mask<{lane_bits}, N, K>",
        "{",
        "    using kernel_t = K;",
        f"    using reg_t = impl::mreg<{lane_bits}, K, impl::lane_reg_bits<{lane_bits}, N, K>>;",
        "    using bits_t = std::conditional_t<(N > 32), u64, u32>;",
        "",
        "    static constexpr int lanes = N;",
        f"    static constexpr int registers = {r};",
        "    static constexpr bool generated = true;",
        "    static constexpr bool is_loop_free = true;",
        "",
        f"    typename reg_t::type _r[{r}];",
        "",
    ]
    for name in ("bit_and", "bit_or", "bit_xor"):
        lines += _fn(f"CC_FORCE_INLINE mask {name}(mask b) const",
                     ["mask m;"] + _each(r, f"m._r[{{i}}] = reg_t::{name}(_r[{{i}}], b._r[{{i}}]);") + ["return m;"])
    lines += _fn("CC_FORCE_INLINE mask bit_not() const",
                 ["mask m;"] + _each(r, "m._r[{i}] = reg_t::bit_not(_r[{i}]);") + ["return m;"])
    lines += ["", "    /// Bit i is lane i; there is no bits() beyond 64 lanes."]
    lines += _fn("CC_FORCE_INLINE bits_t bits() const",
                 ['static_assert(N <= 64, "cimd::mask::bits(): more than 64 lanes do not fit one integer");']
                 + [f"bits_t b = bits_t(reg_t::bits(_r[0]));"]
                 + [f"b |= bits_t(reg_t::bits(_r[{i}])) << ({i} * reg_t::lanes);" for i in range(1, r)]
                 + ["return b;"])
    lines += _fn("static CC_FORCE_INLINE mask from_bits(bits_t b)",
                 ["mask m;"] + _each(r, "m._r[{i}] = reg_t::from_bits(u32(b >> ({o})));") + ["return m;"])
    lines += ["    /// Whether any lane is set; cheaper than `bits() != 0` on kernels without a movemask."]
    lines += _fn("CC_FORCE_INLINE bool any() const", _tree(r, "reg_t::bit_or({a}, {b})") + ["return reg_t::any(x0);"])
    lines += _fn("CC_FORCE_INLINE bool all() const", _tree(r, "reg_t::bit_and({a}, {b})") + ["return reg_t::all(x0);"])
    lines += _fn("CC_FORCE_INLINE bool none() const", ["return !any();"])
    lines += [
        "",
        "    /// `a` where the lane is set, `b` where it is not; `b` may be a scalar of exactly the element type.",
        "    template <class T>",
        f"        requires(sizeof(T) * 8 == {lane_bits})",
    ]
    lines += _fn("CC_FORCE_INLINE simd<T, N, K> select(simd<T, N, K> a, std::type_identity_t<simd<T, N, K>> b) const",
                 ["simd<T, N, K> v;"]
                 + _each(r, "v._r[{i}] = simd<T, N, K>::reg_t::select(_r[{i}], a._r[{i}], b._r[{i}]);")
                 + ["return v;"])
    lines += [""]
    for name, sym in (("bit_and", "&"), ("bit_or", "|"), ("bit_xor", "^")):
        lines += [f"    CC_FORCE_INLINE friend mask operator{sym}(mask a, mask b) {{ return a.{name}(b); }}",
                  f"    CC_FORCE_INLINE mask& operator{sym}=(mask b) {{ return *this = {name}(b); }}"]
    lines += ["    CC_FORCE_INLINE friend mask operator~(mask a) { return a.bit_not(); }", "};", ""]
    return lines


def emit_fixed_masks() -> str:
    lines = header("Masks of every lane width, by mask-register count, for every kernel at once.")
    lines += ["#include <clean-simd/simd.hh>", "", "#include <clean-core/common/assert.hh>", "",
              "#include <type_traits>", "", "// NOLINTBEGIN", ""]
    for lane_bits in LANE_BITS:
        for r in REGISTER_COUNTS:
            lines += emit_mask(lane_bits, r)
    lines += ["// NOLINTEND", ""]
    return "\n".join(lines)


def emit_fixed(e: Elem) -> str:
    lines = header(f"cimd::simd<{e.name}, N, K> by register count, for every kernel at once.")
    lines += ["#include <clean-simd/generated/fixed/masks.hh>", "#include <clean-simd/simd.hh>", "",
              "#include <clean-core/common/assert.hh>", "", "#include <type_traits>", "", "// NOLINTBEGIN", ""]
    for r in REGISTER_COUNTS:
        lines += emit_value(e, r)
    lines += ["// NOLINTEND", ""]
    return "\n".join(lines)
