#include "pipeline_fields.hh"

#include <clean-core/container/vector.hh>
#include <clean-core/string/format.hh>
#include <shaped-graphics-language/driver/impl/front_end.hh>

using namespace sgl;

namespace
{
constexpr cc::string_view k_description = "raster_pipeline_description";
constexpr cc::string_view k_color_targets = "color_targets";

/// One leaf of the mirror.
struct leaf
{
    /// From the description down, a target's fields under `color_targets` with no target named.
    cc::vector<cc::string> names;
    /// `bool`, `int` or `float`, or the enum's name.
    cc::string type;
    bool is_enum = false;
};

void leaves_of(check::checked_module const& m, check::type_id type, cc::vector<cc::string> names, cc::vector<leaf>& out)
{
    auto const& t = m.at(type);
    auto const is_struct = t.kind == check::type_kind::structure && m.builtin_type_of(type) == nullptr;
    if (!is_struct)
    {
        out.push_back({.names = cc::move(names), .type = cc::string(m.name_of(type)), .is_enum = m.is_plain_enum(type)});
        return;
    }
    for (auto const& member : m.at(t.members))
    {
        auto next = names;
        next.push_back(member.name);
        leaves_of(m, member.type, cc::move(next), out);
    }
}

cc::string joined(cc::span<cc::string const> names, cc::string_view separator, isize from = 0)
{
    auto out = cc::string();
    for (auto i = from; i < names.size(); ++i)
    {
        if (i > from)
            out += separator;
        out += names[i];
    }
    return out;
}

bool is_target(leaf const& l)
{
    return !l.names.empty() && l.names[0] == k_color_targets;
}

/// The C++ a setter writes its value `v` with.
cc::string assignment_of(leaf const& l)
{
    auto const target = cc::string("d.color_targets[target]");
    if (is_target(l) && l.names.size() == 3 && l.names[1] == "write_mask")
        return cc::format("{}.write_mask.set(sg::color_channel::{}, v);", target, l.names[2]);

    auto field = cc::format("d.{}", joined(l.names, "."));
    if (is_target(l) && l.names.size() > 2 && l.names[1] == "blend")
        // Writing one field of a blend switches it on, over sg's defaults for the rest.
        field = cc::format("engaged({}).{}", target, joined(l.names, ".", 2));
    else if (is_target(l))
        field = cc::format("{}.{}", target, joined(l.names, ".", 1));

    // SGL has one int, and sg holds some of them narrower, such as a u8 stencil mask; the checker kept it in range.
    if (!l.is_enum && l.type == "int")
        return cc::format("{} = decltype({})(v);", field, field);
    return cc::format("{} = v;", field);
}

cc::string parameter_of(leaf const& l)
{
    if (l.is_enum)
        return cc::format("sg::{}", l.type);
    return l.type == "float" ? cc::string("float") : l.type == "bool" ? cc::string("bool") : cc::string("int");
}

cc::string kind_of(leaf const& l)
{
    if (l.is_enum)
        return "enum_case";
    return l.type == "float" ? cc::string("real") : l.type == "bool" ? cc::string("boolean") : cc::string("integer");
}

cc::string value_of(leaf const& l)
{
    if (l.is_enum)
        return cc::format("sg::{}(v.integer)", l.type);
    return l.type == "float" ? cc::string("float(v.real)")
         : l.type == "bool"  ? cc::string("v.integer != 0")
                             : cc::string("int(v.integer)");
}
} // namespace

cc::string sgl::pipeline_fields_text()
{
    auto const front = driver::impl::run_front_end("", "<pipeline-fields>");
    auto const& m = front.module;
    auto description = check::type_id::none;
    for (auto const& s : m.symbols)
        if (s.name == k_description && s.kind == check::symbol_kind::structure)
            description = s.type;
    auto leaves = cc::vector<leaf>();
    leaves_of(m, description, {}, leaves);

    auto out = cc::string();
    out += "// GENERATED by `sgl pipeline-fields` from the SGL prelude's mirror of sg::raster_pipeline_description.\n";
    out += "// Never edit it: `uv run dev.py check sgl-prelude --fix` rewrites it, and the check fails while it "
           "differs.\n";
    out += "// Every setter names an sg field and every case an sg enumerator, so a mirror that drifted from sg does "
           "not "
           "compile.\n";
    out += "#pragma once\n\n";
    out += "// clang-format off\n\n";
    out += "#include <shaped-shader-library/impl/pipeline_field_support.hh>\n\n";
    out += "namespace slib::impl::fields\n{\n";

    // ---- the setters
    out += "// ---- one setter per field; a generated pipeline calls these directly\n\n";
    for (auto const& l : leaves)
    {
        auto const name = joined(l.names, "_");
        auto const target = is_target(l) ? ", int target" : "";
        out.appendf("inline void {}(sg::raster_pipeline_description& d{}, {} v) {{ {} }}\n", name, target,
                    parameter_of(l), assignment_of(l));
    }
    out += "/// `blend = .none`: the target does not blend.\n";
    out += "inline void color_targets_blend_none(sg::raster_pipeline_description& d, int target) "
           "{ d.color_targets[target].blend = {}; }\n";

    // ---- the enums, each once, in the order the fields first use them
    out += "\n// ---- each enum's cases by name, for a reload\n\n";
    auto enums = cc::vector<cc::string>();
    for (auto const& l : leaves)
    {
        auto is_new = l.is_enum;
        for (auto const& e : enums)
            is_new = is_new && e != l.type;
        if (is_new)
            enums.push_back(l.type);
    }
    for (auto const& e : enums)
    {
        out.appendf("inline constexpr enum_case cases_{}[] = {{\n", e);
        for (auto const& s : m.symbols)
            if (s.name == e && s.kind == check::symbol_kind::enumeration)
                for (auto const& c : m.at(m.at(s.type).cases))
                    out.appendf("    {{\"{}\", int(sg::{}::{})}},\n", c.name, e, c.name);
        out += "};\n";
    }
    out += "inline constexpr named_enum enums[] = {\n";
    for (auto const& e : enums)
        out.appendf("    {{\"{}\", cases_{}}},\n", e, e);
    out += "};\n";

    // ---- the reload table
    out += "\n// ---- every field by its path, `*` for a target: what a reloaded setting is applied through\n\n";
    out += "inline constexpr field all[] = {\n";
    for (auto const& l : leaves)
    {
        auto path = cc::vector<cc::string>();
        for (auto i = isize(0); i < l.names.size(); ++i)
        {
            path.push_back(l.names[i]);
            if (i == 0 && is_target(l))
                path.push_back("*");
        }
        auto const call = is_target(l) ? cc::format("{}(d, target, {})", joined(l.names, "_"), value_of(l))
                                       : cc::format("{}(d, {})", joined(l.names, "_"), value_of(l));
        out.appendf("    {{\"{}\", field_kind::{}, {}, [](sg::raster_pipeline_description& d, int{}, field_value v) {{ "
                    "{}; }}}},\n",
                    joined(path, "."), kind_of(l), l.is_enum ? cc::format("cases_{}", l.type) : cc::string("{}"),
                    is_target(l) ? " target" : "", call);
    }
    out += "    {\"color_targets.*.blend\", field_kind::none, {}, [](sg::raster_pipeline_description& d, int target, "
           "field_value) { color_targets_blend_none(d, target); }},\n";
    out += "};\n";
    out += "} // namespace slib::impl::fields\n\n// clang-format on\n";
    return out;
}
