#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///

"""
Embed the HTML-export front-end assets into a generated C++ header.

Reads report/html/app.css and report/html/app.js and writes a header exposing them as
`itrace::html::app_css` / `itrace::html::app_js` raw-string literals, so the shipped .exe needs no
external files. Run by CMake as a build step whenever the sources change (see CMakeLists.txt); can
also be run by hand:

    uv run tools/instruction-tracer/embed-html-assets.py <out-header>

Defaults the output to report/html/generated/html_assets.hh next to the sources when no path given.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
HTML_DIR = HERE / "src" / "instruction-tracer" / "report" / "html"

# Raw-string delimiters chosen so ordinary CSS/JS never contains them. We still assert their absence
# rather than silently emit a header that will not compile.
ASSETS = [
    ("app_css", HTML_DIR / "app.css", "CSSRAW"),
    ("app_js", HTML_DIR / "app.js", "JSRAW"),
]


def main() -> int:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else HTML_DIR / "generated" / "html_assets.hh"

    parts = [
        "// Generated by tools/instruction-tracer/embed-html-assets.py — do not edit.",
        "// Source: report/html/app.css, report/html/app.js",
        "#pragma once",
        "",
        "namespace itrace::html",
        "{",
    ]

    for name, path, delim in ASSETS:
        if not path.exists():
            print(f"embed-html-assets: missing asset {path}", file=sys.stderr)
            return 1
        text = path.read_text(encoding="utf-8")
        token = f'){delim}"'
        if token in text:
            print(
                f"embed-html-assets: {path.name} contains the raw-string delimiter {token!r}; "
                f"pick a different delimiter in embed-html-assets.py",
                file=sys.stderr,
            )
            return 1
        # MSVC caps a single string literal at ~16 KB (C2026), so split the asset into adjacent
        # raw-string literals the compiler concatenates. 4000 chars stays well under the limit even
        # if every char were a 4-byte UTF-8 sequence. The chunk boundary can fall anywhere — the
        # delimiter token is asserted absent above, so no chunk can close the literal early.
        parts.append(f"inline constexpr char const* {name} =")
        for start in range(0, len(text), 4000):
            parts.append(f'R"{delim}({text[start : start + 4000]}){delim}"')
        parts.append(";" if text else '""; // (empty asset)')
        parts.append("")

    parts.append("} // namespace itrace::html")
    parts.append("")

    content = "\n".join(parts)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # Avoid rewriting (and so retriggering the build) when nothing changed.
    if out_path.exists() and out_path.read_text(encoding="utf-8") == content:
        return 0
    out_path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
